name: "License header checker"
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ".github/scripts/check_license_headers.sh"
